name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Test Http Client
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Run the test using docker intellij-http-client image
        run: |
          ./run.sh
        shell: bash
